config/routes.rb
Rails.application.routes.draw do
  resources :field_offices
  resources :form_n400s
  root 'welcome#index'
  devise_for :users
  resources :citizen_forms
  # resources :user_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/field_office.rb
class FieldOffice < ApplicationRecord
  # belongs_to :form_n400
end

app/controllers/field_offices_controller.rb
class FieldOfficesController < ApplicationController
  before_action :set_field_office, only: [:show, :edit, :update, :destroy]

  # GET /field_offices
  # GET /field_offices.json
  def index
    @field_offices = FieldOffice.all
  end

  # GET /field_offices/1
  # GET /field_offices/1.json
  def show
  end

  # GET /field_offices/new
  def new
    @field_office = FieldOffice.new
  end

  # GET /field_offices/1/edit
  def edit
  end

  # POST /field_offices
  # POST /field_offices.json
  def create
    @field_office = FieldOffice.new(field_office_params)

    respond_to do |format|
      if @field_office.save
        format.html { redirect_to @field_office, notice: 'Field office was successfully created.' }
        format.json { render :show, status: :created, location: @field_office }
      else
        format.html { render :new }
        format.json { render json: @field_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_offices/1
  # PATCH/PUT /field_offices/1.json
  def update
    respond_to do |format|
      if @field_office.update(field_office_params)
        format.html { redirect_to @field_office, notice: 'Field office was successfully updated.' }
        format.json { render :show, status: :ok, location: @field_office }
      else
        format.html { render :edit }
        format.json { render json: @field_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_offices/1
  # DELETE /field_offices/1.json
  def destroy
    @field_office.destroy
    respond_to do |format|
      format.html { redirect_to field_offices_url, notice: 'Field office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_office
      @field_office = FieldOffice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_office_params
      params.require(:field_office).permit(:state, :name)
    end
end

app/helpers/field_offices_helper.rb
module FieldOfficesHelper
end

app/views/field_offices/_form.html.erb
<%= simple_form_for(@field_office) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :state %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/field_offices/edit.html.erb
<h1>Editing Field Office</h1>

<%= render 'form', field_office: @field_office %>

<%= link_to 'Show', @field_office %> |
<%= link_to 'Back', field_offices_path %>

app/views/field_offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Field Offices</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th>Form n400</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @field_offices.each do |field_office| %>
      <tr>
        <td><%= field_office.state %></td>
        <td><%= field_office.name %></td>
        <td><%= link_to 'Show', field_office %></td>
        <td><%= link_to 'Edit', edit_field_office_path(field_office) %></td>
        <td><%= link_to 'Destroy', field_office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field Office', new_field_office_path %>

app/views/field_offices/new.html.erb
<h1>New Field Office</h1>

<%= render 'form', field_office: @field_office %>

<%= link_to 'Back', field_offices_path %>

app/views/field_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @field_office.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @field_office.name %>
</p>


<%= link_to 'Edit', edit_field_office_path(@field_office) %> |
<%= link_to 'Back', field_offices_path %>