config/routes.rb
Rails.application.routes.draw do
  resources :field_offices
  resources :form_n400s
  root 'welcome#index'
  devise_for :users
  resources :citizen_forms
  # resources :user_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/citizen_forms_controller.rb
class CitizenFormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_citizen_form, only: [:show, :edit, :update, :destroy]

  # GET /citizen_forms
  # GET /citizen_forms.json
  def index
    @citizen_forms = CitizenForm.all
  end

  # GET /citizen_forms/1
  # GET /citizen_forms/1.json
  def show
  end

  # GET /citizen_forms/new
  def new
    @citizen_form = CitizenForm.new
  end

  # GET /citizen_forms/1/edit
  def edit
  end

  # POST /citizen_forms
  # POST /citizen_forms.json
  def create
    @citizen_form = CitizenForm.new(citizen_form_params)
    @citizen_form.user_id = current_user.id

    respond_to do |format|
      if @citizen_form.save
        format.html { redirect_to @citizen_form, notice: 'Citizen form was successfully created.' }
        format.json { render :show, status: :created, location: @citizen_form }
      else
        format.html { render :new }
        format.json { render json: @citizen_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citizen_forms/1
  # PATCH/PUT /citizen_forms/1.json
  def update
    respond_to do |format|
      if @citizen_form.update(citizen_form_params)
        format.html { redirect_to @citizen_form, notice: 'Citizen form was successfully updated.' }
        format.json { render :show, status: :ok, location: @citizen_form }
      else
        format.html { render :edit }
        format.json { render json: @citizen_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citizen_forms/1
  # DELETE /citizen_forms/1.json
  def destroy
    @citizen_form.destroy
    respond_to do |format|
      format.html { redirect_to citizen_forms_url, notice: 'Citizen form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citizen_form
      @citizen_form = CitizenForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def citizen_form_params
      params.require(:citizen_form).permit(:name, :date_of_birth, :bio, :twitter, :github, :website, :user_id)
    end
end

app/helpers/citizen_forms_helper.rb
module CitizenFormsHelper
end

app/views/citizen_forms/_form.html.erb
<%= simple_form_for(@citizen_form, html: {id: 'SignupForm'}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
    <fieldset>
      <legend>Personal</legend>
      <%= f.input :name %>
      <%= f.input :date_of_birth %>
      <%= f.input :bio %>          
    </fieldset>

    <fieldset>
      <legend>Socials</legend>
      <%= f.input :twitter %>
      <%= f.input :github %>
      <%= f.input :website %>
    </fieldset>
    <%#= f.association :user %>


  <div class="form-actions">
    <%= f.button :submit, id: 'SaveAccount' %>
  </div>
<% end %>

app/views/citizen_forms/edit.html.erb
<h1>Editing Citizen Form</h1>

<%= render 'form', citizen_form: @citizen_form %>

<%= link_to 'Show', @citizen_form %> |
<%= link_to 'Back', citizen_forms_path %>

app/views/citizen_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Citizen Forms</h1>
<% if current_user.citizen_form %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Date of birth</th>
        <th>Bio</th>
        <th>Twitter</th>
        <th>Github</th>
        <th>Website</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @citizen_forms.each do |citizen_form| %>
        <% if current_user == citizen_form.user %>
          <tr>
            <td><%= citizen_form.name %></td>
            <td><%= citizen_form.date_of_birth %></td>
            <td><%= citizen_form.bio %></td>
            <td><%= citizen_form.twitter %></td>
            <td><%= citizen_form.github %></td>
            <td><%= citizen_form.website %></td>
            <td><%= citizen_form.user.email %></td>
            <td><%= link_to 'Show', citizen_form %></td>
            <td><%= link_to 'Edit', edit_citizen_form_path(citizen_form) %></td>
            <td><%= link_to 'Destroy', citizen_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>      
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= link_to 'New Citizen Form', new_citizen_form_path %>
<%  end %>

app/views/citizen_forms/new.html.erb
<h1>New Citizen Form</h1>

<%= render 'form', citizen_form: @citizen_form %>

<%= link_to 'Back', citizen_forms_path %>

app/views/citizen_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @citizen_form.name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @citizen_form.date_of_birth %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @citizen_form.bio %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @citizen_form.twitter %>
</p>

<p>
  <strong>Github:</strong>
  <%= @citizen_form.github %>
</p>

<p>
  <strong>Website:</strong>
  <%= @citizen_form.website %>
</p>

<p>
  <strong>User:</strong>
  <%= @citizen_form.user.email %>
</p>

<%= link_to 'Edit', edit_citizen_form_path(@citizen_form) %> |
<%= link_to 'Back', citizen_forms_path %>